[book]
authors = ["GreenDelta"]
language = "en"
multilingual = false
src = "src"
title = "openLCA 2 manual"
theme = "Rust"

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 1         # the depth to start folding
